{ pkgs, config, ... }:

{
  home = {
    packages = with pkgs; [
      angband
      anki
      audacity
      bitwarden
      bk
      cargo
      cinnamon.nemo
      cryptsetup
      deno
      discord
      dunst
      eza
      feh
      ffmpeg-full
      file
      fzf
      gcc
      gimp
      go
      htop
      imagemagick
      luajit
      luajitPackages.magick
      luarocks
      lutris
      lxappearance
      maim
      mpc-cli
      mpd
      mpv
      newsboat
      nodePackages_latest.bash-language-server
      nodePackages_latest.pyright
      nodePackages_latest.readability-cli
      nodejs
      openssl
      pkg-config
      popcorntime
      porsmo
      prismlauncher
      qalculate-gtk
      qbittorrent
      rust-analyzer
      rustc
      sc-im
      slides
      sxiv
      telegram-desktop
      texlive.combined.scheme-full
      thunderbird
      tuir
      ueberzugpp
      unrar-wrapper
      unzip
      wezterm
      wiki-tui
      wineWowPackages.staging
      xclip
      youtube-tui
      yt-dlp
      zip
      ];
  };

}
